#%RAML 1.0 
baseUri: https://mocksvc.mulesoft.com/mocks/765c0c12-c331-4eed-b463-3160a572eae3 # baseUri: https://mocksvc.mulesoft.com/mocks/dfe96a2b-b982-484d-8c72-00cfc8f4fddc # 
title: Catalog API

version: 1.0
mediaType: application/json

uses:
  product: /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/catalog-datatypes/1.0.6/productTypes.raml
  traits: /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/commons-traits/1.0.0/traits.raml

resourceTypes:
  collection: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/commons-resourcetypes/1.0.1/collection.raml
  member: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/commons-resourcetypes/1.0.1/member.raml

/catalog:
  /products:
    type:
      collection:
        response-type: product.ProductData
        request-type: product.NewProductData
        response-example:  !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/catalog-examples/1.0.15/ProductCollectionExample.raml
    /{product_id}:
      type:
        member:
          get-response-example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/catalog-examples/1.0.15/ProductExample.raml
          get-response-type: product.ProductData
          patch-response-type: product.ProductData
    /price/{price}:
      type:
        collection:
          response-type: product.ProductData
          request-type: product.NewProductData
          response-example:  !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/catalog-examples/1.0.15/ProductCollectionExample.raml