[
  {
    login: "jconnor",
    fullName: "John Connor",
    email: "jconnor@gmail.com",
    avatar: {
      id: 4321,
      url: http://cdn.playbuzz.com/cdn/65e0d76d-1693-468b-841c-7703a7796e36/8958a07c-484d-4da0-8cff-f2fceb55dde8.jpg
    },
    address: {
      country: "USA",
      state: "CA",
      city: "San Francisco",
      street_address: "77 Geary St #400",
      zip: "94108"
    }
  }
  {
    login: "sconnor",
    fullName: "Sarah Connor",
    email: "sconnor@outlook.com",
    avatar: {
      id: 4321,
      url: https://amp.businessinsider.com/images/59c27c3f38d20d2a008b8842-750-563.jpg
    },
    address: {
      country: "USA",
      state: "CA",
      city: "San Francisco",
      street_address: "77 Geary St #400",
      zip: "94108"
    }
  }
]
