#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/72f1b03f-d069-4c3e-8011-975d0a18c9ec #
title: Catalog API

version: 1.0
mediaType: application/json

uses:
  product: dataTypes/productTypes.raml
  traits: ../Commons-API/traits/traits.raml

resourceTypes:
  collection: !include ../Commons-API/resourceTypes/collection.raml
  member: !include ../Commons-API/resourceTypes/member.raml

/catalog:
  /products:
    type:
      collection:
        response-type: product.ProductData
        request-type: product.NewProductData
        response-example:  !include examples/ProductCollectionExample.raml
    /{product_id}:
      type:
        member:
          get-response-example: !include examples/ProductExample.raml
          get-response-type: product.ProductData
          patch-response-type: product.ProductData
    /price/{price}:
      type:
        collection:
          response-type: product.ProductData
          request-type: product.NewProductData
          response-example:  !include examples/ProductCollectionExample.raml
