#%RAML 1.0 NamedExample
outcome_id: 612009
type: tent camping
answers:
  - question_id: 1001
    answer: Rob Hill Campground
  - question_id: 1002
    answer: in two weeks
  - question_id: 1003
    answer: five
  - question_id: 1004
    answer: yes, 2 girls