#%RAML 1.0 Library

usage: Product Types
uses:
  util: ../../Commons-API/datatypes/utilTypes.raml
  company: ../../Commons-API/datatypes/companyTypes.raml
  
types:
  NewProductData:
    properties:
      price: util.MonetaryAmountData
      description: string
      copy: string
      image: util.ImageData
      company: company.Company
      category: string
      review?: util.ReviewData[]

  ProductData:
    type: NewProductData
    properties:
      id: number
