#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/2f8f2e60-27a6-48c9-b492-fd7993bd1bc4 # 
title: Outcomes API

version: 1.0
mediaType: application/json

uses:
  outcomes: /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/outcomes-datatypes/1.0.5/outcomes-datatypes.raml

/outcomes:
  get:
    queryParameters: 
      keywords:
        type: string[]
    description: Returns a outcomes.NewOutcomesResponse
    responses:
      200:
        body:
          type: outcomes.NewOutcomesResponse
          example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/outcomes-examples/1.0.9/new-outcomes-response-examples.raml
  /{outcome_type}:
    get:
      description: Returns a outcomes.NewOutcomesResponse
      responses:
        200:
          body:
            type: outcomes.NewOutcomesResponse
            example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/outcomes-examples/1.0.9/new-outcomes-response-examples.raml
  /outcome:
    post:
      description: Creating a outcomes.OutcomesRequest
      body:
        type: outcomes.OutcomesRequest
        example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/outcomes-examples/1.0.9/outcomes-request-example.raml
      responses:
        201:
          headers:
            Content-Location:
              type: string
              example: https://outcomes-app.cloudhub.io/api/outcomes/outcome/1234
    /{outcome_id}:
      get:
        description: Retrieve a created outcome
        responses:
          200:
            body:
              type: outcomes.OutcomesResponse
              example: !include exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/outcomes-examples/1.0.9/outcomes-response-example.raml