#%RAML 1.0 Library

usage: Inventory Types
uses:
  location: ../../Commons-API/dataTypes/locationTypes.raml
types:
  Inventory:
    properties:
      product_id: number
      quantity: number
      location: location.AddressData
