#%RAML 1.0
version: v1
title: social-recommendations-api
mediaType: application/json

types:
  ArtPiece:
    type: string
  PaintColor:
    type: string
  Choices:
    properties:
      artPieces: ArtPiece[]
      paintColors: PaintColor[]
  ChoiceResults:
    properties:
      artPiece: ArtPiece
      paintColor: PaintColor
      count: integer
      latest: string[]
  Recommendation:
    properties:
      clientId:
      name:
      choice:
        type: integer[]
        minItems: 2
        maxItems: 2


/choices:
  get:
    responses:
      200:
        body:
          type: Choices
          example:
            {
              "artPieces": [
                "http://3.bp.blogspot.com/_6QdxFZPFLoY/S2-Ocuy_c-I/AAAAAAAAAiw/C1eeBZmr_20/S760/Figura23.jpg"
                ,"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfvDeYw3OqpVQNpYG3_qq6JsbJuoQ683CbSYbSUfROoV_84pLdvA"
                ,"https://cdn.mensagenscomamor.com/content/images/p000005352.jpg?v=0"
              ],
              "paintColors": [
                "red", "green", "blue"
              ]
            }
  put:
    headers:
      Authorization:
    body:
      type: Choices
      example:
        {
          "artPieces": [
            "http://3.bp.blogspot.com/_6QdxFZPFLoY/S2-Ocuy_c-I/AAAAAAAAAiw/C1eeBZmr_20/S760/Figura23.jpg", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfvDeYw3OqpVQNpYG3_qq6JsbJuoQ683CbSYbSUfROoV_84pLdvA", "https://cdn.mensagenscomamor.com/content/images/p000005352.jpg?v=0"
          ],
          "paintColors": [
            "red", "green", "blue"
          ]
        }
    responses:
      200:
        body:
          type: Choices
          example:
            {
              "artPieces": [
                "http://3.bp.blogspot.com/_6QdxFZPFLoY/S2-Ocuy_c-I/AAAAAAAAAiw/C1eeBZmr_20/S760/Figura23.jpg", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfvDeYw3OqpVQNpYG3_qq6JsbJuoQ683CbSYbSUfROoV_84pLdvA", "https://cdn.mensagenscomamor.com/content/images/p000005352.jpg?v=0"
              ],
              "paintColors": [
                "red", "green", "blue"
              ]
            }

/recommendations:
  post:
    body:
      type: Recommendation
      example: {
          "clientId": "1",
          "name": "Janet",
          "choice": [0,2]
        }
    responses: 
      200:
        body:
          type: Recommendation
          example: {
            "clientId": "1",
            "name": "Janet",
            "choice": [0,2]
          }
  put:
    headers:
      Authorization:
    body:
      type: Recommendation[]
      example: [{
          "clientId": "1",
          "name": "Janet",
          "choice": [2,0]
        }]
    responses: 
      200:
        body:
          type: Recommendation[]
          example: [{
            "clientId": "1",
            "name": "Janet",
            "choice": [0,2]
          }]
  /summary:
    get:
      responses: 
        200:
          body:
            type: ChoiceResults[][]
    /top:
      get:
        responses:
          200:
            body:
              type: ChoiceResults