#%RAML 1.0
version: v1
title: social-recommendations-api
mediaType: application/json

types:
  ArtPiece:
    type: string
  PaintColor:
    type: string
  Choices:
    properties:
      artPieces: ArtPiece[]
      paintColors: PaintColor[]
  ChoiceResults:
    properties:
      artPiece: ArtPiece
      paintColor: PaintColor
      count: integer
      latest: string[]
  Recommendation:
    properties:
      clientId:
      name:
      choice:
        type: integer[]
        minItems: 2
        maxItems: 2


/choices:
  get:
    responses:
      200:
        body:
          type: Choices
          example:
            {
              "artPieces": [
                "fig1", "fig2", "fig3"
              ],
              "paintColors": [
                "red", "green", "blue"
              ]
            }
  put:
    headers:
      Authorization:
    body:
      type: Choices
      example:
        {
          "artPieces": [
            "fig1", "fig2", "fig3"
          ],
          "paintColors": [
            "red", "green", "blue"
          ]
        }
    responses:
      204:

/recommendations:
  post:
    body:
      type: Recommendation
      example: {
          "clientId": "1",
          "name": "Janet",
          "choice": [0,2]
        }
    responses: 
      201:
        headers:
          Content-location:
            type: string
            example: https://social-recommendation-app.cloudhub.io/api/recommendations/summary
  put:
    headers:
      Authorization:
    body:
      type: Recommendation
      example: {
          "clientId": "1",
          "name": "Janet",
          "choice": [2,0]
        }
    responses:
      204:
        headers:
          Content-location:
            type: string
            example: https://localhost:8082/api/recommendations/summary
  /summary:
    get:
      responses: 
        200:
          body:
            type: ChoiceResults[][]
    /top:
      get:
        responses:
          200:
            body:
              type: ChoiceResults