#%RAML 1.0 Library

usage: Product Types
uses:
  util: utilTypes.raml
  company: companyTypes.raml
types:
  ProductData:
    properties:
      id: number
      price: util.MonetaryAmountData
      description: string
      copy: string
      image: util.ImageData
      company: company.Company 
      category: util.CategoryData
      review?: util.ReviewData[]
      
  NewProductData:
    type: ProductData
    properties: 
      price: util.MonetaryAmountData
      description: string
      copy: string
      image: util.ImageData
      company: company.Company
      category: util.CategoryData
      review?: util.ReviewData[]