#%RAML 1.0
title: product-finder

uses:
  productData: dataTypes/productTypes.raml
resourceTypes: 
  collection: !include resourceTypes/collection.raml
  collection-item: !include resourceTypes/collection-item.raml
/products:
  type: 
    collection:
      response-type: productData.ProductData
      request-type: productData.NewProductData
  get:
    queryParameters: 
      category:
        description: "The category the product belongs to (case insensitie and doesn't need to match the whole name)"
        type: string
        example: outdoor sports
        required: false
      company:
        description: "The name of the company the product belongs to (case insensitie and doesn't need to match the whole name)"
        type: string
        example: Sports Basement
        required: false
  /{product_id}:
    type:
      collection-item:
        get-response-example: !include examples/ProductExample.raml
        get-response-type: productData.ProductData
        patch-response-type: productData.ProductData