#%RAML 1.0 Library

usage: Order Types
uses:
  product: ../../Catalog-API/dataTypes/productTypes.raml

types:
  ShippedStatus:
    enum: [shipped, non-shipped, canceled]

  OrderProduct:
    properties:
      id: number
      amount: number

  NewOrder:
    properties:
      totalAmountPrice: number
      totalAmountPriceCurrency: string
      shippingStatus: ShippedStatus
      customerID: number
      products: OrderProduct[]

  Order:
    type: NewOrder
    properties:
      id: number
