#%RAML 1.0
title: Ordering API

version: 1.1
mediaType: application/json

uses:
  order: /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/ordering-datatypes/1.0.1/orderTypes.raml
  customer: /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/customer-datatypes/1.0.1/customer-datatypes.raml
  traits: /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/commons-traits/1.0.0/traits.raml

resourceTypes:
  collection: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/commons-resourcetypes/1.0.1/collection.raml
  member: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/commons-resourcetypes/1.0.1/member.raml

/ordering:
  /orders:
    type:
      collection:
        response-type: order.NewOrder
        request-type: order.Order
        response-example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/ordering-examples/1.0.0/OrderCollectionExample.raml
    /{order_id}:
      type:
        member:
          get-response-example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/ordering-examples/1.0.0/OrderExample.raml
          get-response-type: order.Order
          patch-response-type: order.Order
    /customer/{customer_id}:
      type:
        collection:
          response-type: order.NewOrder
          request-type: order.Order
          response-example: !include /exchange_modules/a6d4cdc7-ecb0-4315-a6a6-216c71ba0b54/ordering-examples/1.0.0/OrderCollectionExample.raml
