#%RAML 1.0 NamedExample
{
  id: 321,
  orderProducts: {
      products: [{
          id: 789,
          amount: 2,
          shippingStatus: non-shipped
        },
        {
          id: 567,
          amount: 1,
          shippingStatus: non-shipped
        }],
      totalAmountPrice: 120.00,
      totalAmountPriceCurrency: USD
    },
  customerID: 20180355
}
