[
  {
    id: 321,
    orderProducts: {
        products: [{
            id: 789,
            amount: 2,
            shippingStatus: non-shipped
          },
          {
            id: 567,
            amount: 1,
            shippingStatus: non-shipped
          }],
        totalAmountPrice: 120.00,
        totalAmountPriceCurrency: USD
      },
    customerID: 20180355
  },
  {
    id: 456,
    orderProducts: {
        products: [{
            id: 765,
            amount: 1,
            shippingStatus: shipped
          }]
        totalAmountPrice: 7.99,
        totalAmountPriceCurrency: USD
      },
    customerID: 20180354
  }
]
