[
  {
    id: 123,
    products: [
    {
      id: 1,
      amount: 2
    },
    {
      id: 2,
      amount: 1
    }],
    totalAmountPrice: 130.00,
    totalAmountPriceCurrency: USD,
    shippingStatus: non-shipped,
    customerID: 20180355
  },
  {
    id: 321,
    products: [
    {
      id: 789,
      amount: 2
    },
    {
      id: 567,
      amount: 1
    }],
    totalAmountPrice: 120.00,
    totalAmountPriceCurrency: USD,
    shippingStatus: non-shipped,
    customerID: 20180355
  }
]